raft
vlad17/princeton-cos418-review pull request #7
Opened 2017-01-18 03:32 UTC by jl25

2017-01-18 19:13 UTC, vlad17 requested changes

2017-01-18 19:13 UTC, vlad17 commented on raft/README.md
Cite raft pls since we're using their images.

2017-01-18 19:13 UTC, vlad17 commented on raft/README.md
> +* If an **electionTimeout** (150-300ms) passes with no heartbeat, the follower assumes the leader has crashed and starts a new election.
not leader behavior

2017-01-18 19:13 UTC, vlad17 commented on raft/README.md
> +
missing leader behavior: send proposals (nonempty appendentries). Can only send proposals from current term bc of figure 8

2017-01-18 19:13 UTC, vlad17 commented on raft/README.md
> +* Respond to RPCs from candidates and leader
Vague: just say what it actually does - on heartbeat, reset election timer

On leader append entries, update entries.

2017-01-18 19:13 UTC, vlad17 commented on raft/README.md
> +* Equivalent to (multi-)Paxos
it's not equivalent except that it's distributed consensus, which you already said.

2017-01-18 19:42 UTC, vlad17 commented
Can you also please add what makes a log stale?
 
That's the only other nontrivial detail I think you're missing. Then raft is done.

2017-01-21 16:21 UTC, vlad17 requested changes

2017-01-21 16:21 UTC, vlad17 commented on chord/README.md
> +The following examples are for adding `N36`, where the initial state is `N25 -> N40`. `N40` has keys `K30` and `K38`.
has keys K26, K30, K38

2017-01-21 16:21 UTC, vlad17 commented on chord/README.md
> +item, and storing the key/data item pair at the node to which the key maps. It is efficient (`O(log N)` messages per lookup) and scalable (`O(log N)` state per node), where N is the total number of s
Expected runtime

2017-01-21 16:21 UTC, vlad17 commented on chord/README.md
> +Each node stores a list of its `r` immediate successor, so after failure, the first live succesor is known.
successors

2017-01-21 16:21 UTC, vlad17 commented on chord/README.md
> +Lookup(key-id)	look in local finger table and successor-list			  for highest n: my-id < n < key-id	if n exists		  call Lookup(key-id) on node n	 // next hop		  if call failed,			  remove n from
can you change these carriage returns into newlines?

2017-01-21 16:21 UTC, vlad17 commented on chord/README.md
> +* Robust despite massive failure
Mention virtualized nodes here; with N^2 virtual nodes a node failure only increases load on each node by 1/N in expectation.

2017-01-21 16:21 UTC, vlad17 commented on primary-backup/README.md
> +## Examples
Separate the examples with ### sections - it's hard to distinguish which text refers to what

2017-01-21 16:21 UTC, vlad17 commented on primary-backup/README.md
> +In this example, the client has the old view and tries to contact the primary, who also has the old view. When the primary forwards the command to `S2`, `S2` rejects the request. The client's request
contact the **old** primary

2017-01-21 16:21 UTC, vlad17 commented on primary-backup/README.md
> +TODO: Why doesn't the primary update its own view?
That's a mistake on their part. the primary should infer it, since a higher view can only be in use by a previous-backup if that backup was acked as up-to-date by the primary to the view, which then must've told the previous-backup it is the new primary. In a partition the view change didn't reach the primary, which still thinks it's the leader, but if the previous-backup-now-primary changed views then you can assume the view knows about it.

2017-01-21 16:21 UTC, vlad17 commented on raft/README.md
> +* On receiving nonempty append entries from leader, update log entries
and reset

2017-01-21 16:21 UTC, vlad17 commented on roofnet/README.md
> +Wireless interface IP addresses are auto configured, using a private prefix (e.g. 10) for the high byte, and the lower 24 bits of ethernet addresses for the lower three bytes.
All this prose could be condensed:
* Wireless interface IP based on hardware ethernet address for low bytes -> no config
* Every box has a NAT for its users -> no address allocation necessary

2017-01-21 16:21 UTC, vlad17 commented on roofnet/README.md
> +Roofnet assumes that a small fraction of Roofnet users will voluntarily share their wired Internet acces links.
access

2017-01-21 16:21 UTC, vlad17 commented on roofnet/README.md
> +Practical studies found that minimum-hop-count routes are significantly throughput-suboptimal, so we must choose paths with care. This is hard to predict because link loss is often asymmetric, and th
rm "so we must choose paths with care. This is hard to predict"

2017-01-21 16:21 UTC, vlad17 commented on roofnet/README.md
> +Practical studies found that minimum-hop-count routes are significantly throughput-suboptimal, so we must choose paths with care. This is hard to predict because link loss is often asymmetric, and th
ie just say

Practical studies found that minimum-hop-count routes are significantly throughput-suboptimal: link loss can be high-variance and asymmetric.

2017-01-21 16:21 UTC, vlad17 commented on roofnet/README.md
> +* Gateways periodically flood queries for a non-existent destination address, so that everyone learns the route to the gateway
Gateways flood queries? Really? I must've missed that...

2017-01-21 16:21 UTC, vlad17 commented on roofnet/README.md
> +Can't compare two transmissions at different bitrates (802.11b supports 1, 2, 5.5, and 11 Mbit/s). RoofNet uses ETT to predict which links offer the best throughput.
what are the diff bitrates for again? Why cant we use 11?

2017-01-21 16:21 UTC, vlad17 commented on roofnet/README.md
> +Can't compare two transmissions at different bitrates (802.11b supports 1, 2, 5.5, and 11 Mbit/s). RoofNet uses ETT to predict which links offer the best throughput.
i think it's interference or something. just mention that

2017-01-21 16:21 UTC, vlad17 commented on rpc/README.md
> +* If the application has its own functionality to cope with duplication and reordering
of what? RPCs, I presume

2017-01-21 16:21 UTC, vlad17 commented on rpc/README.md
> +* Read-only operations with no side effects
not necessarily - just have to be idempotent ops

2017-01-21 16:21 UTC, vlad17 commented on rpc/README.md
> +* Read-only operations with no side effects
(idempotent and commutative)

2017-01-21 16:21 UTC, vlad17 commented on rpc/README.md
> +## Networking (Basics)
lol wtf just get rid of this section

2017-01-21 16:21 UTC, vlad17 commented on rpc/README.md
> +
Wasn't there also soemthing about exactly-once? I.e., combine both schemes? I recall this was what we were told golang did, right?

2017-01-21 16:21 UTC, vlad17 commented on transactions/README.md
> +* **Page**, with a page log sequence number, which uniquely identifies the log record for the latest update applied to this page.
What does a page contain? Multiple key/values?

2017-01-21 16:21 UTC, vlad17 commented on transactions/README.md
> +* Dirty page table: a page identifer table for dirty pages. It uses a recovery log sequence number, which tracks the earliest change to that page that is *not on disk*
don't define "dirty page table" with "dirty pages" (i.e., say "pages with un-fsynced data")

2017-01-21 16:21 UTC, vlad17 commented on transactions/README.md
> +### Stable Storage
Confusing - only log is always-stable. Pages can be both

2017-01-21 16:21 UTC, vlad17 commented on transactions/README.md
> +1. Start at **checkpointed** entries in the T-table and dirty page table.
start -> Initialize from persisted tables corresponding to log checkpoint

2017-01-21 16:21 UTC, vlad17 commented on transactions/README.md
> +3. Figure out which transactions committed since the checkpoing, and which failed.
checkpoing

2017-01-21 16:21 UTC, vlad17 commented on transactions/README.md
> +1. Start at the first log sequence number and scan log entries forward in time. Reapply **all actions** and update the page log sequence numbers.
"first log sequence number"? first relative to what? an image from the ppt would be helpful here

2017-01-21 16:21 UTC, vlad17 commented on transactions/README.md
> +2. State now matches state as recorded by log.
This isn't really an operation, it's just an observation. Maybe you could rm this and just detail 1 a bit more?

2017-01-21 16:21 UTC, vlad17 commented on transactions/README.md
> +1. Scan log entries backwards from the end and undo all transactions that have failed.
Yeah again picture/more detail would be helpful here. Also, wasn't there some note about crashing during crash recovery?

2017-01-21 16:51 UTC, jl25 commented on chord/README.md
> +* Robust despite massive failure
How?

2017-01-21 16:59 UTC, jl25 commented on chord/README.md
> +* Robust despite massive failure
Isn't this the case with N nodes too? If a physical node fails all its virtual nodes will fail as well.

2017-01-21 17:03 UTC, vlad17 commented on chord/README.md
> +* Robust despite massive failure
No. If we have N virtual (1 virt per phys), then failing one phys means all of its keys go to its successor. If we have N^2 virtual (still O(lg N) lookup) then failing one node means its keys are split among the N different virtual successors it has, which map to O(N) different physical successors in expectation).

2017-01-21 17:16 UTC, jl25 commented on roofnet/README.md
> +* Gateways periodically flood queries for a non-existent destination address, so that everyone learns the route to the gateway
It's in the paper

2017-01-21 17:24 UTC, jl25 commented on rpc/README.md
> +
Yeah, i chose to leave it out but i can put in a quick blurb about it

2017-01-21 17:39 UTC, jl25 commented on transactions/README.md
> +* **Page**, with a page log sequence number, which uniquely identifies the log record for the latest update applied to this page.
Pretty sure its just data - multiple key values

2017-01-21 17:44 UTC, jl25 commented on transactions/README.md
> +1. Start at the first log sequence number and scan log entries forward in time. Reapply **all actions** and update the page log sequence numbers.
yeah all the indices are pretty complicated... i'll put some slides in but its a lot of detail that gets into implementation

2017-01-21 17:47 UTC, jl25 commented on transactions/README.md
> +1. Scan log entries backwards from the end and undo all transactions that have failed.
I didn't see it, let me know if you find it

2017-01-21 17:47 UTC, vlad17 commented on transactions/README.md
> +1. Start at the first log sequence number and scan log entries forward in time. Reapply **all actions** and update the page log sequence numbers.
that's ok, it's the detailed explanation section

2017-01-21 17:48 UTC, vlad17 commented on transactions/README.md
> +* **Page**, with a page log sequence number, which uniquely identifies the log record for the latest update applied to this page.
just mention that

2017-01-21 17:48 UTC, jl25 commented on transactions/README.md
> +1. Scan log entries backwards from the end and undo all transactions that have failed.
I'd imagine that its just the same process...

2017-01-21 17:51 UTC, vlad17 commented on transactions/README.md
> +1. Scan log entries backwards from the end and undo all transactions that have failed.
"Log every change, even undo operations during crash recovery
– Helps for repeat crashes"

2017-01-21 18:14 UTC, vlad17 requested changes
one last thing

2017-01-21 18:14 UTC, vlad17 commented on chord/README.md
> +* With `N^2` virtual nodes, a node failure only increases the load on each node by `1/N` on expectation
1/N of the load in expectation, compared to the case of N virtual nodes.

2017-01-21 18:32 UTC, merged